-- 1. CLEANUP (Wipe the slate clean)
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.classification CASCADE;
DROP TABLE IF EXISTS public.account CASCADE;
DROP TYPE IF EXISTS public.account_type CASCADE;

-- 2. STRUCTURE (Create tables and types)
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

CREATE TABLE public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type public.account_type NOT NULL DEFAULT 'Client'::public.account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id),
    CONSTRAINT account_email_unq UNIQUE (account_email)
);

CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

CREATE TABLE public.inventory (
    inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT NULL,
    inv_model character varying NOT NULL,
    inv_year character(4) NOT NULL,
    inv_description text NOT NULL,
    inv_image character varying NOT NULL,
    inv_thumbnail character varying NOT NULL,
    inv_price numeric(9, 0) NOT NULL,
    inv_miles integer NOT NULL,
    inv_color character varying NOT NULL,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id),
    CONSTRAINT fk_classification FOREIGN KEY (classification_id)
        REFERENCES public.classification (classification_id)
        ON UPDATE CASCADE ON DELETE NO ACTION
);

-- 3. DATA INSERTION (Fill the tables)
INSERT INTO public.classification (classification_name)
VALUES ('Custom'), ('Sport'), ('SUV'), ('Truck'), ('Sedan');

INSERT INTO public.inventory (inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id)
VALUES 
('Chevy', 'Camaro', '2018', 'If you want to feel the power this is the car for you.', '/images/camaro.jpg', '/images/camaro-tn.jpg', 25000, 10123, 'Silver', 2),
('Batmobile', 'Custom', '2007', 'Ever want to be a super hero? now you can with the batmobile.', '/images/batmobile.jpg', '/images/batmobile-tn.jpg', 65000, 21800, 'Black', 1),
('FBI', 'Surveillance Van', '2016', 'Have a neighbor you dont like? or just want to watch people?', '/images/survan.jpg', '/images/survan-tn.jpg', 20000, 19851, 'Brown', 4),
('Dog', 'Car', '1997', 'Do you like dogs? do you like cars? then this is the car for you.', '/images/dogcar.jpg', '/images/dogcar-tn.jpg', 35000, 71832, 'White', 1),
('Jeep', 'Wrangler', '2019', 'The Jeep Wrangler is the most iconic vehicle in the world.', '/images/wrangler.jpg', '/images/wrangler-tn.jpg', 28000, 4123, 'Yellow', 3),
('Lamborghini', 'Adventador', '2016', 'This car is fast. Very fast.', '/images/adventador.jpg', '/images/adventador-tn.jpg', 80000, 3500, 'Blue', 2),
('Aerocar', 'International', '1954', 'Are you tired of traffic? fly over it with the Aerocar.', '/images/aerocar.jpg', '/images/aerocar-tn.jpg', 1000000, 18956, 'Red', 1),
('Monster', 'Truck', '1995', 'Crush the competition with this monster truck.', '/images/monster.jpg', '/images/monster-tn.jpg', 150000, 3998, 'Purple', 4),
('GM', 'Hummer', '2016', 'Do you have a lot of money and want to spend it? get a Hummer.', '/images/hummer.jpg', '/images/hummer-tn.jpg', 58000, 23145, 'Green', 4),
('Mechanic', 'Special', '1964', 'This car is a fixer upper. It needs a lot of work.', '/images/mspecial.jpg', '/images/mspecial-tn.jpg', 100, 200123, 'Rust', 5),
('Ford', 'Model T', '1921', 'The Ford Model T is the first car ever made.', '/images/modelt.jpg', '/images/modelt-tn.jpg', 30000, 100, 'Black', 5),
('Mystery', 'Machine', '1999', 'Scooby and the gang are ready for an adventure.', '/images/mmachine.jpg', '/images/mmachine-tn.jpg', 10000, 128564, 'Green', 4),
('Spartan', 'Fire Truck', '2012', 'Emergencies happen. Be ready with this fire truck.', '/images/fire-truck.jpg', '/images/fire-truck-tn.jpg', 200000, 18000, 'Red', 4),
('Ford', 'Crown Victoria', '2013', 'The Ford Crown Victoria is a classic police car.', '/images/crown-vic.jpg', '/images/crown-vic-tn.jpg', 10000, 108245, 'Silver', 5);

-- 4. FINAL UPDATES (Task 4 & 6 copied from assignment2.sql)
UPDATE public.inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

UPDATE public.inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');